#pragma once

#define ORION_MOUSE_BUTTON_1         0
#define ORION_MOUSE_BUTTON_2         1
#define ORION_MOUSE_BUTTON_3         2
#define ORION_MOUSE_BUTTON_4         3
#define ORION_MOUSE_BUTTON_5         4
#define ORION_MOUSE_BUTTON_6         5
#define ORION_MOUSE_BUTTON_7         6
#define ORION_MOUSE_BUTTON_8         7
#define ORION_MOUSE_BUTTON_LAST      ORION_MOUSE_BUTTON_8
#define ORION_MOUSE_BUTTON_LEFT      ORION_MOUSE_BUTTON_1
#define ORION_MOUSE_BUTTON_RIGHT     ORION_MOUSE_BUTTON_2
#define ORION_MOUSE_BUTTON_MIDDLE    ORION_MOUSE_BUTTON_3